version: "3.7"
services:
  ruby:
    build: ./ruby
    environment:
      - MYSQL_HOSTNAME=mysql
      - MYSQL_PORT=3306
    volumes:
      - .:/isucon10/isucon10-final/webapp
    ports:
      - 50051:50051